#! /bin/sh
#
#  $Id$
#

test_exit()
{
  exit_code=$1
  exit $exit_code
}

progname=${0##*/}        # fast basename hack for ksh, bash

USAGE=\
"usage: $progname [ -opts ] test [ test ... ]
"

check_status()
{
  if [ $1 -ne 0 ] ; then
    shift 
    echo "FAILED: " "$*" >&2
    exit 1
  fi
}


if [ X${RTEMS_MAKEFILE_PATH} = X ] ; then
  echo RTEMS_MAKEFILE_PATH not set
  exit 1
fi

echo "Generating RTEMS_SETTINGS file..."
make -f Makefile.settings clean all
check_status $? Could not generate RTEMS_SETTINGS

source ./RTEMS_SETTINGS

PREFIX=${BSPTOP}

echo WARNING USING ${PREFIX} for install point!!!

do_step()
{
  case $1 in
    rmlogs)
      rm -f */build.log */c.log */clean.log */distclean.log */install.log
      ;;
    configure)
      echo "configuring jpeg-7 ..."
      cd jpeg-7
      CFLAGS="${CPU_CFLAGS}" \
         ./configure --host=${TARGET} --prefix=${PREFIX} \
         --includedir=${PREFIX}/lib/include \
         --disable-shared \
         --disable-programs \
         >c.log 2>&1
      check_status $? Could not configure jpeg-7

      cd ../tiff-3.9.2
      check_status $? Could not cd to tiff-3.9.2

      echo "configuring tiff-3.9.2 ..."
      CFLAGS="${CPU_CFLAGS}" \
         ./configure --host=${TARGET} --prefix=${PREFIX} \
         --includedir=${PREFIX}/lib/include \
         --disable-shared \
         >c.log 2>&1
      check_status $? Could not configure tiff-3.9.2

      cd ../libpng-1.2.41
      echo "configuring libpng-1.2.41 ..."
      # include BSP_CFLAGS so it sees libz
      CFLAGS="${BSP_CFLAGS} ${CPU_CFLAGS}" \
         ./configure --host=${TARGET} --prefix=${PREFIX} \
         --includedir=${PREFIX}/lib/include \
         --disable-shared \
         >c.log 2>&1
      check_status $? Could not configure libpng-1.2.41

      cd ../freetype-2.3.11
      echo "configuring freetype-2.3.11 ..."
      # include BSP_CFLAGS so it sees libz
      CFLAGS="${BSP_CFLAGS} ${CPU_CFLAGS}" \
         ./configure --host=${TARGET} --prefix=${PREFIX} \
         --includedir=${PREFIX}/lib/include \
         --disable-shared \
         >c.log 2>&1
      check_status $? Could not configure freetype-2.3.11

      cd ../t1lib-5.1.2
      echo "configuring t1lib-5.1.2 ..."
      # include BSP_CFLAGS so it sees libz
      CFLAGS="${BSP_CFLAGS} ${CPU_CFLAGS}" \
         ./configure --host=${TARGET} --prefix=${PREFIX} \
         --includedir=${PREFIX}/lib/include \
         --datadir=${PREFIX}/share \
         --disable-shared \
         --without-athena --without-x \
         >c.log 2>&1
      check_status $? Could not configure t1lib-5.1.2

      cd ..
      ;;
    build|clean|distclean|install)
      action=${1}
      if [ ${1} = build ] ; then
        action=
      fi

      for d in jpeg-7 tiff-3.9.2 libpng-1.2.41 freetype-2.3.11 t1lib-5.1.2
      do
        echo "Performing ${1} on ${d} ..."

        cd ${d}
        check_status $? Could not cd to ${d}
        make ${action} >${1}.log 2>&1

        if [ ${1} != distclean ] ; then
          check_status $? Could not ${1} in ${d}
        fi
        #if [ ${1} = distclean ] ; then
        #  rm -f build.log c.log clean.log distclean.log
        #fi
        cd ..
      done

      echo "Performing ${1} on rtems-nano-x ..."
      case $1 in
        build|clean|install)
          #cd rtems-nano-x
          #make -C microwin/src -f Makefile.rtems ${action}
          #check_status $? Could not ${1} in rtems-nano-x
          #cd ..
          ;;
        *)
          ;;
      esac
      ;;
    *)
      check_status 1 Unknown action ${1}
      ;;
  esac
}

for a in $*
do
  do_step ${a}
done

exit 0
